// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package tip

import (
	"server/api/tip"
)

type ControllerV1 struct{}

func NewV1() tip.ITipV1 {
	return &ControllerV1{}
}
