// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"context"
	"server/internal/dao/internal"
	"server/internal/model/do"
	"server/internal/model/entity"
)

// internalAdminMenuDao is an internal type for wrapping the internal DAO implementation.
type internalAdminMenuDao = *internal.AdminMenuDao

// adminMenuDao is the data access object for the table admin_menu.
// You can define custom methods on it to extend its functionality as needed.
type adminMenuDao struct {
	internalAdminMenuDao
}

var (
	// AdminMenu is a globally accessible object for table admin_menu operations.
	AdminMenu = adminMenuDao{
		internal.NewAdminMenuDao(),
	}
)

// Add your custom methods and functionality below.

func Create(ctx context.Context, menu *entity.AdminMenu) (int64, error) {
	res, err := AdminMenu.Ctx(ctx).Insert(menu)

	id, err := res.LastInsertId()

	if err != nil {
		return 0, err
	}

	return id, err
}

func ExistById(ctx context.Context, id uint) (exist bool, err error) {
	exist, err = AdminMenu.Ctx(ctx).Exist(do.AdminMenu{
		Id: id,
	})
	return
}

func ExistByPath(ctx context.Context, path string) (exist bool, err error) {
	exist, err = AdminMenu.Ctx(ctx).Exist(do.AdminMenu{
		Path: path,
	})
	return
}
