// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"server/internal/dao/internal"
)

// internalReptileConfigDao is an internal type for wrapping the internal DAO implementation.
type internalReptileConfigDao = *internal.ReptileConfigDao

// reptileConfigDao is the data access object for the table reptile_config.
// You can define custom methods on it to extend its functionality as needed.
type reptileConfigDao struct {
	internalReptileConfigDao
}

var (
	// ReptileConfig is a globally accessible object for table reptile_config operations.
	ReptileConfig = reptileConfigDao{
		internal.NewReptileConfigDao(),
	}
)

// Add your custom methods and functionality below.
